/**
 * Plain-language guides for the calculators.
 *
 * Written for someone who runs machines, not a trading desk: no term is used
 * before it is explained, and where the honest answer is "this does not matter
 * at your size", the copy says so. Every input entry names where to find your
 * own number, because a calculator whose inputs you have to guess is a toy.
 *
 * Labels here must match the Slider labels in components/tools/ verbatim.
 */

export type ToolGuideContent = {
  /** Publishing metadata for the standalone long-form guide at /academy/guides/<slug>. */
  article: { title: string; seoTitle: string; summary: string; publishedAt: string }
  whatItIs: string
  whoFor: string
  howToUse: string[]
  inputs: { label: string; means: string; whereToFind: string; typical: string }[]
  readingResults: { figure: string; means: string; soWhat: string }[]
  walkthrough: { title: string; setup: string; steps: string[]; takeaway: string }
  mistakes: string[]
  limits: string[]
}

export const TOOL_GUIDES: Record<string, ToolGuideContent> = {
  "hosting-effective-rate": {
    article: {
      title: "What your hosting contract really costs",
      seoTitle: "Hosting effective rate: what you really pay per kWh",
      summary: "Hosting quotes hide fees and idle hours. Turn an advertised $/kWh into the real cost of a kWh that earns bitcoin.",
      publishedAt: "2026-08-31",
    },
    whatItIs: "Your hosting contract quotes a price per kilowatt-hour. You never actually pay that price. This tool works out what you really pay for each kilowatt-hour that earns you bitcoin. It adds the extra charges on top, then takes off the hours your machines sat idle. Here is why the idle hours matter. You pay for the power you booked whether your machines run or not. You only earn while they run. So every lost hour still has to be paid for out of the hours that are left, and that pushes the cost of those hours up. The answer is a number for comparing quotes. Run two hosting offers through it and you can see which one is really cheaper.",
    whoFor: "This is for you if someone else runs your machines, and you are choosing between contracts or checking the one you already signed. Not the right tool where you run your own site and buy power straight from the utility. Your energy charge falls when your machines stop, so idle hours do not push up the price of the kilowatt-hours you did use — the rate on your bill is already close to your true rate. The one part of your bill that behaves like a hosting contract is the demand charge, which is set by your highest peak in the month and does not fall when you switch off. This tool will not size that for you. Take last month's demand charge in dollars, divide it by the kilowatt-hours you actually hashed on, and add that figure to your energy rate by hand. It also has nothing to offer if your deal is not priced per kilowatt-hour at all. If your host takes a share of the bitcoin you mine, or sells you hashrate rather than space and power, there is no advertised rate to start from and this tool cannot rank that deal against anything. A flat all-in price per machine per month can be converted, though. Divide the monthly price by the machine's power draw in kilowatts multiplied by 730 hours, and enter the result as the advertised rate with both fee sliders at 0%. A $256 per machine per month all-in price on a 3.5 kW machine is $256 divided by 2,555 kilowatt-hours, which is $0.100 per kilowatt-hour.",
    howToUse: [
      "Get your hosting contract and your invoices in front of you before you touch a slider. Twelve months of invoices if you can get them, not three — the hours a site loses swing hard with the season, so a short winter sample can flatter a contract badly. Almost every number below comes off one of those two documents.",
      "Set \"Advertised power rate\" to the headline price in your contract, in dollars per kilowatt-hour. The slider moves in steps of $0.001 per kilowatt-hour, a tenth of a cent, and stops at $0.20 per kilowatt-hour. Now add the two extras the host puts on your bill: \"Management fee\" and \"Power factor extra\". You type both in as a percentage of your power bill.",
      "Set the two lost-hours sliders from your own pool records rather than from what the host advertises. \"Unplanned downtime\" means the hours your machines stopped because something broke. \"Curtailment\" means the hours your host deliberately switches your machines off. Count each lost hour once. If an hour is already counted in one slider, do not count it again in the other.",
      "Set \"Pool fee\" to what your mining pool takes, then read the large number at the top right. That is your cost per kilowatt-hour that actually earns bitcoin.",
      "Copy the web address into a note or email it to yourself before you touch the sliders for the second contract, then run the whole thing again for that contract. Any slider you moved away from its starting value gets saved into that address automatically, so pasting it back later brings the first contract straight back — and without it, the first set is gone. Sliders you left alone are missing from the address on purpose, and open at their starting values at the other end. Two things that go with that. Nothing is stored anywhere, so closing the tab loses whatever you have not copied. And anyone you send that address to can read your contract terms off it, so think before you paste it into a group chat that has a host in it. \"Reset\" puts all six sliders back to their starting values.",
      "Ask a question with your two numbers rather than signing. Go back to whichever host looks worse and ask for two things in writing: the real curtailed and outage hours at your building, month by month for the last twelve months, and their definition of uptime — specifically, whether curtailed hours count against it. Put their answers in and run it again. A host who will not give you either has told you roughly what the number would have been."
    ],
    inputs: [
      { label: "Advertised power rate",
        means: "The headline price per kilowatt-hour in your contract — the number the salesperson leads with. Everything else in this tool is an adjustment to it. The slider runs from $0.000 to $0.200 per kilowatt-hour in steps of $0.001 per kilowatt-hour, and starts at $0.065 per kilowatt-hour.",
        whereToFind: "The pricing schedule of your hosting agreement, usually on page one or two. Then check it against reality. Take last month's invoice. Find the power or energy line. Divide the dollars by the kilowatt-hours on that same invoice. If the answer is not the rate in your contract, the difference is one of the other sliders below. If your rate is above $0.200 per kilowatt-hour the slider will not reach it. Enter half your rate and double every dollar figure the tool hands back — the effective rate, the after-fees row and the after-lost-hours row all scale straight up, and the percentage above the advertised rate does not change at all. The tool does not care which currency the numbers are in, as long as both contracts you are comparing are in the same one.",
        typical: "Most hosting quotes land between $0.045 and $0.085 per kilowatt-hour. Anything under $0.040 per kilowatt-hour usually means the host switches your machines off a lot — that is curtailment — and putting a price on exactly that is what this tool is for." },
      { label: "Management fee",
        means: "What the host charges for running the machines, on top of the electricity — you put it in as a percentage of the power bill. The tool applies it to the advertised rate. At 5%, an advertised $0.065 per kilowatt-hour becomes $0.0683 per kWh before anything else happens.",
        whereToFind: "The fees or services clause of your contract, and the invoice line called management, service, hosting or O&M (operations and maintenance). If it is charged in dollars rather than as a percentage, convert it first — see the mistakes section below. Some contracts have no separate fee at all and bury it in the rate; in that case put 0%.",
        typical: "3% to 10% of the power bill is the usual band. The slider goes up to 30%, far above any normal contract. That extra room is only there for people who had to turn a flat monthly fee into a percentage first — see the mistakes section." },
      { label: "Power factor extra (if billed on kVA)",
        means: "Some hosts bill you for the power your site pulls off the grid, not the power your machines actually turn into hashing. Those are not the same number. Electrical gear always draws a bit more than it uses, and mining rigs are worse than most. The size of that gap is measured by something called power factor, and kVA is the unit the grid uses when it bills you this way. The tool adds this on as a flat percentage of the advertised rate, the same way it handles the management fee. The two percentages are added together and applied once, not stacked one on top of the other. A 5% management fee and a 3% power factor extra make 8%, so an advertised $0.065 per kilowatt-hour becomes $0.0702 per kilowatt-hour. If your host stacks them the other way round, charging the power factor extra on top of the fee, your invoice will come out a hair higher than this tool shows — about $0.0001 per kilowatt-hour on those figures, which will not change a decision. Same thing, and \"uplift\" there means the extra.",
        whereToFind: "Look on your invoice for a line saying power factor, kVA, reactive power, demand adjustment or similar. If there is not one, ask the site manager one question: am I billed on kW — the power my machines actually use — or on kVA, the larger amount the site pulls off the grid to deliver it. If the answer is kVA and your gear runs at a power factor of 0.95, you are paying for about 5% more power than your machines use, so put in 5%. The sum is 1 divided by 0.95, which is 1.05. If you are billed on kW, put in 0%. To work it out yourself you need your power factor. It is on the spec sheet for the machine's power supply, quoted at full load — most modern miners sit between 0.95 and 0.99 there, and get worse when the machines are throttled or idling. Divide 1 by that number: 1 divided by 0.95 is 1.053, so about 5%; 1 divided by 0.98 is 1.020, so about 2%. Better still, ask your host to read the power factor off your meter. That reading beats any spec sheet, because it is your machines in your building.",
        typical: "0% to 5%. Plenty of contracts have none of this, and 0% is a perfectly normal answer. The starting value of 3% is a middling case, not a rule." },
      { label: "Unplanned downtime",
        means: "The share of hours your machines were not hashing because something broke or went wrong — a tripped breaker, a failed transformer, an internet outage, a fire, a flood, a crew that did not show up. Put it in as a percentage of all the hours you are looking at. If you pulled 90 days of records, it is a percentage of those 90 days. This is the lost time nobody chose. The next slider is the lost time somebody chose on purpose.",
        whereToFind: "Your mining pool's worker or hashrate history is the honest record, because your machines wrote it, not your host. Pull 90 days. Count the hours your hashrate sat at or near zero. Divide that by 2,160, which is the number of hours in 90 days. So 65 hours off comes out at 3%. Your host's monthly uptime report is worth reading, but treat it as their claim, not as a measurement. Pull twelve months if you can, not 90 days, and if 90 days is all you can get, note which 90. Curtailment is seasonal. Three months of winter data from a site that switches off in the summer heat will show you close to 0% of hours and tell you nothing about the contract in front of you. Downtime is less seasonal than that, but transformers still fail in the heat. If this is a new deployment you have no pool history yet, so none of the above is open to you. Do this instead. Ask each host for the outage hours at the specific building you would sit in, month by month for the last twelve months, and enter their figures. Then run it a second time with those hours raised by half — 4% of hours becomes 6% of hours. If the same contract wins both times, the ranking is safe. If it flips, your decision rests entirely on a number the host gave you and you cannot check, and that is worth knowing before you commit machines.",
        typical: "1% to 5% of hours at a site that is run properly. Above 8% of hours, something is genuinely wrong and it is worth a conversation before you sign anything else." },
      { label: "Curtailment",
        means: "The share of hours your machines were switched off deliberately — because power got expensive, or the grid wanted its capacity back, or your host had a deal with the power company. Put it in as a percentage of all the hours you are looking at, the same hours you used for the downtime slider. The tool adds this straight onto downtime: 4% downtime plus 6% curtailment means 10% of hours lost and 90% effective uptime.",
        whereToFind: "Three places. The curtailment notices or emails your host sends you. Your pool history, where curtailment looks different from a breakdown — the whole site stops together, right on the hour, and comes back on the hour. And the curtailment clause in the contract, which tells you the most they are allowed to do, not what they actually did. Ask for the real switched-off hours at your specific building over the last twelve months, not the average across the whole site and not the contract limit. They will answer in hours, and the slider wants a percentage, so convert it yourself. There are 8,760 hours in a year, so 876 curtailed hours is 10% of hours and 300 curtailed hours is about 3.4% of hours. For a single month, use 730 hours. If this is a new deployment you have no pool history yet, so none of the above is open to you. Do this instead. Ask each host for the curtailed hours at the specific building you would sit in, month by month for the last twelve months, and enter their figures. Then run it a second time with those hours raised by half — 10% of hours becomes 15% of hours. If the same contract wins both times, the ranking is safe. If it flips, your decision rests entirely on a number the host gave you and you cannot check, and that is worth knowing before you commit machines.",
        typical: "0% at a site on a fixed price with no deal with the power company. 5% to 15% of hours where the host has agreed to switch off when the grid is short — that deal is usually what pays for their cheap rate. Contracts allowing 20% or more of hours switched off do exist, and they are usually the ones with the lowest advertised price." },
      { label: "Pool fee",
        means: "The cut your mining pool takes out of what you earn, as a percentage. Every other slider on this page is money going out. This one is money taken off the top before it ever reaches you. The tool turns it into a cost per kilowatt-hour so everything can sit in one number. That swap is close but not exact — the limits section at the bottom says by how much and which way. Worth knowing before you set it: if you will use the same pool whichever host you choose, this slider scales both contracts by the same proportion and cannot change which one wins. It is here so that the big number is a true all-in cost, not because it decides anything. Set it the same for both contracts and stop thinking about it.",
        whereToFind: "Your pool's fee page or your account dashboard. It is one of the few numbers here you can look up in under a minute, and one of the few your host has nothing to do with.",
        typical: "0% to 4% of revenue. Around 2% is the common figure on FPPS pools, which pay you a steady amount for the work you send whether or not the pool finds a block; some PPLNS pools, which pay you a share of the blocks the pool actually finds, charge little or nothing. The slider goes to 30%, which no real pool charges." },
    ],
    readingResults: [
      { figure: "Effective rate — the large number at the top of the panel",
        means: "Your all-in cost for one kilowatt-hour that actually earns bitcoin, in dollars, to four decimal places. The hours your machines sat idle are left out of the sum, because those hours paid you nothing.",
        soWhat: "This, not the advertised rate, is the number to write on the comparison sheet when you are choosing between hosts. Two contracts are only comparable on this figure. It is a cost, not a profit — it says nothing about whether you are making money. Once you have both numbers, the last step in the instructions above tells you what to do with them, and it is not to sign." },
      { figure: "The line underneath: \"…% above the advertised $…\"",
        means: "How much bigger the effective rate is than the headline price, as a percentage. At the starting values it reads 22% above the advertised $0.065 per kilowatt-hour. It is rounded to a whole percent, so a small change may not move it.",
        soWhat: "Treat this as your bad-surprise score for that contract. Under about 10% and the quote is close to honest. Over about 40% and you are not buying the thing you were quoted. Go and read the curtailment clause first — that is usually where the difference is hiding." },
      { figure: "Effective uptime",
        means: "100% minus your downtime minus your curtailment, nothing more. At the starting values, 4% plus 6% of hours lost gives 90.0%. The tool does not check this against anything — it is your two sliders added up and taken off 100%.",
        soWhat: "Compare it with the uptime figure your host advertises. If they promise 98% and your own pool records say 90%, then either they broke the promise or they are counting hours differently from you. Both are worth raising before you renew." },
      { figure: "\"After fees\" and \"After lost hours\" — two of the rows in the list",
        means: "Two rows that separate the two kinds of damage, with the uptime figure sitting between them in the list. \"After fees\" is the advertised rate with the management fee and the power factor extra added on. \"After lost hours\" is that figure divided by your effective uptime. The pool fee comes off after that, which is why the big number at the top is a little higher than the \"After lost hours\" row. The last row, \"After pool fee\", is the same number as the big one at the top — the panel repeats it so you can see every step and the answer in one column.",
        soWhat: "Look at which of the two steps moves the number more. At the starting values, the fees add $0.0052 per kilowatt-hour and the lost hours add $0.0078 per kilowatt-hour. The idle time costs you about 50% more than both fees put together. That tells you where to push in a negotiation, and it is usually not the management fee." },
    ],
    walkthrough: {
      title: "Two quotes on the desk, and the cheap one loses",
      setup: "You are placing 500 machines and you have two offers. Host A quotes $0.055 per kilowatt-hour, but Host A has a deal with the power company to switch off when the grid is short, and it switches off hard in summer. Host B quotes $0.070 per kilowatt-hour, has no such deal, and bills you on the power your machines use rather than the power the site draws. On the quote, Host A looks 21% cheaper.",
      steps: [
        "Enter Host A: advertised rate $0.055 per kilowatt-hour, management fee 5% of power, power factor extra 3%, unplanned downtime 4% of hours, curtailment 25% of hours (their own figure for last summer), pool fee 2% of revenue.",
        "Host A comes back at $0.0854 per kilowatt-hour, 55% above the advertised rate. The fees only move it from $0.0550 to $0.0594 per kWh. Then the lost hours do the damage. 4% downtime plus 25% curtailment is 29% of your hours gone, and that takes $0.0594 up to $0.0837 per kWh. The 2% pool fee adds the last bit, taking it to $0.0854 per kWh.",
        "Now enter Host B: advertised rate $0.070 per kilowatt-hour, management fee 3% of power, power factor extra 0%, unplanned downtime 2% of hours, curtailment 0% of hours, pool fee 2% of revenue.",
        "Host B comes back at $0.0751 per kilowatt-hour, 7% above the advertised rate, on 98.0% effective uptime.",
        "Host B is $0.0103 per kilowatt-hour cheaper in real life, even though it is $0.015 per kilowatt-hour dearer on the quote. Work it through. 500 machines drawing 3.5 kW each is 1.75 MW, which is 1,750 kilowatts, and running flat out that is about 42,000 kilowatt-hours a day. At Host B's 98% uptime, about 41,000 of those kilowatt-hours earn. Buying that same 41,000 earning kilowatt-hours from Host A costs about $420 a day more, or roughly $155,000 a year. Be clear about what that compares. At Host A the same 500 machines would only earn for about 29,800 kilowatt-hours a day, so your power bill there would be smaller — and your bitcoin would be smaller with it.",
        "Before you sign with B, go back and ask A one question: what were your actual switched-off hours last year, building by building. If the honest answer is 12% of hours rather than 25%, put that in and run it again. Host A comes back at $0.0722 per kilowatt-hour against Host B's $0.0751 per kilowatt-hour, so A wins after all — but only by $0.0029 per kilowatt-hour, which is about $44,000 a year on those same earning hours. That is real money, and a far smaller margin than the first comparison. Close enough that you would want the 12% written into the contract before you rely on it."
      ],
      takeaway: "The advertised rate ranked these two contracts in the wrong order. The number that decided it was curtailment, which is the one number the host controls, rarely volunteers, and never puts on the quote.",
    },
    mistakes: [
      "Counting the same lost hours twice, or not counting them at all. Hosts often quote \"98% uptime\" and quietly leave the curtailed hours out of that figure, because they planned those ones. So ask them one question: does your 98% include the hours you switched us off? If it does not, their 2% is breakdowns only — put 2% in unplanned downtime, and put your own curtailed hours in the curtailment slider. Those hours sit on top of the 2%, not inside it, and leaving the slider at 0% throws away exactly the hours this tool exists to price. If their 98% does include the switched-off hours, it already covers everything — put 2% in downtime and 0% in curtailment. Only split the two when you have separate records for each. What you must never do is put the same hour in both boxes. Do that and the tool shows you a cost higher than the one you are really paying.",
      "Putting the management fee in as dollars when the slider wants a percentage. This slider wants a percentage of your power bill. If your host charges a flat amount, do the sum first. Say the fee is $20 per machine per month and the machine draws 3.5 kW at the wall. That machine uses 3.5 kW times 730 hours, and 730 is roughly the number of hours in a month, so 2,555 kilowatt-hours. $20 divided by 2,555 kilowatt-hours is $0.0078 per kilowatt-hour. Against an advertised $0.065 per kilowatt-hour, that is 12%, so put 12% in the slider. Use the machine's draw at full power, from its spec sheet or your host's per-machine allocation — not your average metered draw. The tool takes idle hours off further down, and an average draw would take them off twice. Get that sum wrong and every number the tool shows you is wrong with it.",
      "Using the curtailment cap in the contract instead of what actually happened. Some contracts let the host switch you off \"at their discretion\", with no limit at all. Do not put 30% in for that. Do not put 0% in either, on the grounds that it has not bitten you yet. Put in your best honest guess at the real hours. Then ask for last year's actual switched-off hours at your specific building. A host who keeps good records will tell you. A host who will not tell you has told you something more useful.",
      "Forgetting whether tax is in or out. If VAT or sales tax is charged on top of your power bill, one host may quote you with it and the other without, and that gap is bigger than most of the sliders here. Pick one and be consistent across both contracts. If tax is a flat percentage of the power bill you can fold it into the management fee slider. If both contracts carry the same rate of tax you can leave it out of both — it lifts both numbers by the same proportion and will not change which contract wins."
    ],
    limits: [
      "It does not tell you whether you make money. There is no bitcoin price, no machine efficiency in joules per terahash, and no mining difficulty anywhere in the arithmetic. A contract at $0.0751 per kilowatt-hour may be excellent or ruinous depending on your machines and the market, and this tool has no opinion on which.",
      "The pool fee is a rough conversion, not an exact one. The tool takes your power cost and adds the pool's percentage on top: a 2% pool fee adds about $0.0016 per kilowatt-hour to a $0.078 per kilowatt-hour cost. But the pool does not take a cut of your power bill. It takes a cut of what you earn. If you are earning $0.12 for every kilowatt-hour you burn, 2% of that is $0.0024 per kilowatt-hour. So when you are making good money, the tool comes in a bit low on the pool fee. When you are losing money, it comes in a bit high. Either way the gap is under a tenth of a cent per kilowatt-hour in most cases, and it almost never changes which contract wins.",
      "It assumes you keep paying for the power capacity you booked all the way through downtime and curtailment. Most hosting contracts do work that way, but not all. If your host does not bill you for curtailed hours at all, those hours cost you nothing — enter 0% curtailment. You lose the bitcoin, not the money, and this tool measures money. If you are credited for only some of the curtailed hours, enter the hours you still pay for. And if a deal with the power company pays you to switch off, that is money coming in and there is nowhere to put it here. Work that payment out separately and take it off your power bill by hand.",
      "It only counts the six things on the sliders. Left out: deposits, insurance, freight, repair labour, spare parts, and what the machines cost you to buy in the first place. Also left out is the hashrate you lose to dusty or throttled-back machines, and the fact that curtailment tends to land on the hottest days of the year, when your machines are least efficient anyway. Check the answer against your own invoices before you lean on it."
    ],
  },
  "difficulty-exposure": {
    article: {
      title: "What a difficulty move is worth to your fleet",
      seoTitle: "How much bitcoin a difficulty rise costs you",
      summary: "Difficulty decides how much bitcoin your machines earn. Work out what a rise or fall costs you over the weeks ahead.",
      publishedAt: "2026-08-31",
    },
    whatItIs: "Difficulty is the number that decides how much bitcoin your machines earn. When it goes up, the same machines mine less. This tool puts a bitcoin figure on that. You tell it how fast your machines run and how far ahead you are looking. It then shows three things: what you would mine if difficulty rose, what you would mine if it fell, and how much bitcoin sits between those two answers.",
    whoFor: "This is worth running if you have at least about 0.2 EH/s — that is 200,000 TH/s, or roughly 1,000 machines at 200 TH/s each — and a bill you have to meet over the next few months. Between 0.05 and 0.2 EH/s the worst case comes back at about $6,000 to $23,000 over eight weeks at $64,000 a bitcoin: worth knowing before you plan what to sell, rarely worth doing anything else about. Below 0.05 EH/s, roughly 250 machines, the answer comes back small. At 40 machines the worst case is about $900 over eight weeks. If that is you, there is nothing here to act on.",
    howToUse: [
      "Set \"Hashrate\" to what your pool reports as your average, in EH/s. Divide your TH/s by 1,000,000: 3,000 machines at 200 TH/s each is 600,000 TH/s, which is 0.60 EH/s.",
      "Set \"How far ahead\" to the number of weeks you care about. The slider moves in two-week steps, because difficulty changes every 2,016 blocks — about a fortnight. It shows both, like this: 8 weeks (4 difficulty periods).",
      "Set \"Expected fees\" to the transaction fees you expect one block to pay, in BTC. Every block also pays a fixed 3.125 BTC on top. That part never changes, so the tool already has it. Your pool statement lists the fee income separately.",
      "Set the two difficulty sliders — \"Best case: difficulty falls by\" and \"Worst case: difficulty rises by\" — to the biggest fall and the biggest rise you think could really happen over the weeks you picked, as a percentage. The starting numbers, -2.4% and +7.0%, are this site's published range for the next difficulty change only — the one about two weeks away.",
      "Read the big number at the top, then read \"Worst case vs today\" underneath it. They are different numbers. The second one is the one that hits your bank account.",
      "Set \"Bitcoin price\" last. It only changes the dollar figure printed under the big number at the top. Every bitcoin figure on the page stays exactly the same whatever price you pick. One more thing worth knowing: everything you set goes into the page address as you set it. Copy that address and whoever opens it sees your exact numbers — useful when you are sending them to a lender, a host or a partner."
    ],
    inputs: [
      { label: "Hashrate",
        means: "How fast your machines run, in exahash per second (EH/s). One EH/s is 1,000,000 TH/s. A single 200 TH/s machine is 0.0002 EH/s, so it takes about 5,000 of them to make 1 EH/s.",
        whereToFind: "Your mining pool dashboard, under the 7-day or 30-day average. Use that average, not the sticker rating on the machines. The pool average already has your dead hours in it — machines down, or turned down when power is dear. This tool takes whatever number you type and runs it flat out, every hour, for the whole period. Two things the past average does not know about: machines you are about to switch on, and hours you already know you will be off. If a container lands next month, or you are heading into a summer where you expect to be off one hour in ten, type the average you expect across the whole period rather than the one your pool has just measured. For one hour in ten off, knock 10% off the figure: 0.80 EH/s becomes 0.72 EH/s.",
        typical: "The slider runs from 0.01 EH/s to 30 EH/s in steps of 0.01 EH/s, and it starts at 1.00 EH/s. A 15 MW site is roughly 0.80 EH/s. Forty machines at 200 TH/s each is 0.008 EH/s, which the slider will not reach. To use a number that small, add ?eh=0.008 to the end of the page address in your browser and press enter. The sums then use 0.008 EH/s, but do not expect the slider to show it: the thumb sits at the bottom and the label rounds to 0.00 EH/s. Leave that slider alone once the page has loaded. The moment you touch it, your figure is replaced with 0.01 EH/s." },
      { label: "How far ahead",
        means: "How far ahead you are looking. Difficulty changes every 2,016 blocks, which is about two weeks, so the tool counts in two-week steps.",
        whereToFind: "You will not find this anywhere. You pick it. Choose a period you are already committed to: the next three months of hosting invoices, the weeks until a loan payment is due, or however long is left on your power contract.",
        typical: "2 weeks to 26 weeks, in two-week steps, and it starts at 8 weeks (4 difficulty periods). The count starts now and runs in whole two-week blocks. The tool does not know how far into the current two-week period you are, and real difficulty changes rarely land exactly 14 days apart — a busy network gets there early, a quiet one late. If your bill falls on a fixed date, round up rather than down and pick the number of weeks that covers past it." },
      { label: "Expected fees",
        means: "The transaction fees one block pays on top of the fixed 3.125 BTC that every block pays anyway, averaged across the whole period. The tool adds your figure to 3.125 BTC to get what one block is worth, so 0.05 BTC per block makes a block worth 3.175 BTC.",
        whereToFind: "Your pool's payout breakdown lists fee income separately from the fixed 3.125 BTC. A block explorer such as mempool.space shows the fee reward on each recent block. Take an average across a month, not across one busy afternoon.",
        typical: "0 to 0.5 BTC per block, in steps of 0.01 BTC, and it starts at 0.05 BTC per block. Quiet months run lower. A busy week — when the network is jammed and people are paying more to get their transactions through — can be several times higher. The slider stops at 0.5 BTC per block. Do not agonise over this one. Fees are small next to the fixed 3.125 BTC: moving the setting from 0.05 BTC to 0.10 BTC per block changes every bitcoin figure on this page by about 1.5%. Get it roughly right, and spend your time on the hashrate figure instead, where being wrong costs you far more." },
      { label: "Bitcoin price",
        means: "The price used to turn one bitcoin figure into dollars, and nothing else. It does not touch any of the bitcoin numbers, the table, or the production figures. It changes one line: the dollar figure printed under the big number at the top.",
        whereToFind: "Any exchange. Set it a bit below today's price. When difficulty is climbing hardest, the price you sell at is often weak at the same time, so a lower number here gives you a more honest answer.",
        typical: "$20,000 to $200,000 in $1,000 steps, and it starts at $64,000." },
      { label: "Best case: difficulty falls by",
        means: "The furthest difficulty could fall over the weeks you picked, as a percentage. This is the good case: lower difficulty means the same machines earn more bitcoin.",
        whereToFind: "The difficulty forecast page on this site, at /data/difficulty, publishes the range this tool starts with. Block explorers show a live estimate for the next change, based on how fast blocks are arriving right now. Beyond that next change you are making a judgement: look back at the last dozen changes and take the most negative one you see.",
        typical: "0% to 15%, in steps of 0.1%. It starts at 2.4%. This slider stops at 0%, so your best case always includes difficulty staying exactly where it is. There is no way to tell this tool that difficulty is certain to rise." },
      { label: "Worst case: difficulty rises by",
        means: "The furthest difficulty could rise over the weeks you picked, as a percentage. This is the case that costs you bitcoin, and it is the one the tool is really built around.",
        whereToFind: "Same places as the other slider. Take the biggest single rise of the past year. And remember that over several changes the rises pile up: three rises of 3% each leave difficulty about 9% higher, not 3%.",
        typical: "0% to +15% in steps of 0.1%, and it starts at +7.0%. That starting figure describes one difficulty change, about two weeks. For a longer period, set it by looking back over the same number of changes you are looking forward: find where difficulty stood 26 weeks ago, see how far it climbed from there, and use a rise at least that big. As a rough fallback, roughly double your two-week figure for 8 weeks and treble it for 26 weeks — so a +7.0% view of the next fortnight becomes about +14% over 8 weeks and about +21% over 26 weeks. If your figure goes past +15%, the slider cannot reach it. The sum takes ten seconds by hand: divide \"Production at current difficulty\" by 1 plus your percentage. At 22.446 BTC and a 25% rise, 22.446 ÷ 1.25 = 17.96 BTC, which is 4.49 BTC less than today." },
      { label: "Current difficulty",
        means: "There is no slider for this one. To change it you have to edit the page address. It is the difficulty number itself, in trillions, and it is fixed at 127.48 T. The tool uses it to work out how fast the whole network is running: 127.48 T comes out at about 913 EH/s. Difficulty and total network speed are two ways of saying the same thing, because difficulty is set to keep blocks arriving every 10 minutes on average.",
        whereToFind: "Any block explorer, or your pool. To change it, add ?diffT=135.2 to the end of the page address and reload. If you are changing two things at once, the first setting gets a question mark and the second an ampersand: ?eh=0.008&diffT=135.2. If the address already has a question mark in it, every extra setting joins on with an ampersand. Check today's difficulty against 127.48 T before you trust anything on this page. Within about 2% of it, leave it alone. Further than that, every bitcoin figure here is out by roughly the same percentage the other way, and the ten seconds of typing is worth it.",
        typical: "Fixed at 127.48 T, and that figure is illustrative rather than live — there is no data feed behind this site yet, so it was typed in when the tool was built and has not moved since. If real difficulty has moved a long way from it, every bitcoin figure here moves with it. Say real difficulty is 10% higher than 127.48 T: you would really mine about 9% less than this page shows." },
    ],
    readingResults: [
      { figure: "The big number at the top, headed \"Your exposure\" (2.525 BTC with the sliders where they start)",
        means: "Your exposure is the bitcoin at stake in a difficulty move. It is the distance between your two answers: what you mine if difficulty falls, minus what you mine if it rises. It is the gap between two guesses, not bitcoin you lose. The dollar line under it is that same gap multiplied by the price you set.",
        soWhat: "Use it to decide whether this is worth any more of your time. Compare it with your power bill for the same number of weeks. At 1 EH/s over eight weeks it is about 2.5 BTC. At 0.05 EH/s — around 250 machines — it is 0.126 BTC, about $8,000 at $64,000 a bitcoin. At that size, the honest answer is that this does not matter to you." },
      { figure: "Worst case vs today",
        means: "What you lose against your production now if difficulty settles at the top of your range. With the sliders where they start this reads -1.836 BTC, about three quarters of the big number at the top. How much smaller it is depends on where you put the two sliders either side of no change at all, not on how wide you make the gap between them. At -2.4% and +7.0% it is about three quarters. At -7.0% and +7.0% — a wider range, but an even one — it drops to under half.",
        soWhat: "This is the number to take into your cash-flow plan. It is the hole you would have to fill — out of money you have put by, out of bitcoin selling for more than you expected, or by selling machines. The big number at the top will always make that hole look worse than it is. What to do with it: put it next to your fixed bills for the same weeks — hosting, power, loan instalments. Under about 5% of those bills, note it and carry on; it will disappear inside the normal ups and downs of a quarter. Between 5% and 20%, it is a planning job. Hold that much bitcoin back instead of selling it, or agree with your hosting provider now what happens in a month when you are short. Above 20%, it is worth finding out what it would cost to buy a contract that pays you when difficulty rises, and putting that cost next to the figure on this page. This tool cannot tell you whether that is worth doing, because it does not know the price of anything." },
      { figure: "The two \"if difficulty\" lines, and the table below the tool",
        means: "The two lines show what your fleet produces at each end of your range. With the sliders where they start: 28.747 BTC if difficulty falls 2.4%, and 26.222 BTC if it rises 7.0%, against 28.057 BTC if it does not move at all. The table below the tool sets out the same three cases in words. Its last column, \"Versus today\", measures each one against production at today's difficulty: +0.690 BTC if difficulty falls 2.4%, and -1.836 BTC if it rises 7.0%. Every figure in the table is bitcoin. The price you set does not touch it.",
        soWhat: "Everything else on the page is built from these two lines. The big number at the top is the gap between them. \"Worst case vs today\" is the lower one minus your production at today's difficulty. If a figure on the page surprises you, work back to these two before you doubt anything else. The table is there so you can lift the three figures into a spreadsheet or an email without dragging sliders, and so a search engine or an AI assistant reading the page can see the numbers at all." },
      { figure: "Production at current difficulty, and Network hashrate",
        means: "Production at current difficulty is what your fleet mines over the weeks you picked if difficulty does not move at all — 28.057 BTC for 1 EH/s over eight weeks. It is before any pool fee and before any lost hours. Network hashrate is the combined speed of every miner on earth, about 913 EH/s. It is worked out from the difficulty figure rather than measured, so it does not move when the network speeds up or slows down between changes.",
        soWhat: "Check production against what your pool actually paid you over a similar stretch. To compare like with like, take your pool fee off the tool's figure first. If your pool keeps 2%, multiply by 0.98: 28.057 BTC becomes 27.50 BTC. Then allow another 1% to 3% for hours you were down. If your pool statement still comes in more than about 5% below that, the hashrate you typed is too high, and nothing else on this page is worth reading until you fix it. For a second check, divide your own speed by the network hashrate to see what share of all mining is yours. At 1 EH/s your share is about 0.11%. The whole network mines about 6,401 BTC every two weeks, if fees run at 0.05 BTC per block. If your pool payments work out at a very different share, something you have typed is wrong." },
    ],
    walkthrough: {
      title: "A 15 MW site looking two months ahead",
      setup: "You run about 4,000 machines at 200 TH/s each on a 15 MW site. That is 0.80 EH/s. You have eight weeks of hosting invoices coming. You plan to sell bitcoin to pay them, and you want to know how much of that bitcoin could vanish if mining gets harder.",
      steps: [
        "Set \"Hashrate\" to 0.80 EH/s. Leave \"How far ahead\" at 8 weeks (4 difficulty periods), and leave \"Expected fees\" at 0.05 BTC per block.",
        "Leave the two difficulty sliders where they start, at -2.4% and +7.0%, and set \"Bitcoin price\" to $64,000.",
        "Read \"Production at current difficulty\": 22.446 BTC. That is your eight-week baseline if difficulty does not move.",
        "Read the two lines below it. If difficulty falls 2.4% you mine 22.998 BTC. If it rises 7.0% you mine 20.977 BTC. The big number at the top, 2.020 BTC — printed as $129,303 on the line beneath it — is the gap between those two. It is not a loss.",
        "Read \"Worst case vs today\": -1.468 BTC. The tool prints that one in bitcoin only, so do the dollars yourself: at $64,000 a bitcoin that is about $94,000. That is the hole if difficulty jumps to +7.0% now and stays there for all eight weeks. If it instead climbs in even steps across the four difficulty changes — the usual way — you lose nearer 0.9 BTC, about $60,000, and less again if most of the rise lands near the end. Plan against the $94,000, because that is the bad end, but expect to land somewhere in the middle.",
        "Put that $94,000 next to your power bill for the same eight weeks. At 15 MW and $0.05 per kilowatt-hour, that bill is about $1,008,000, so the worst case is roughly 9% of it."
      ],
      takeaway: "For a 15 MW site the number that matters is \"Worst case vs today\" — about 1.5 BTC over eight weeks if difficulty jumps straight to the top of your range, nearer 0.9 BTC if it climbs in steps — and not the larger figure printed at the top. That is real money. It is also under a tenth of your power bill for the same eight weeks. So the first move is to plan for it, and put the money by, not to go looking for a contract to buy.",
    },
    mistakes: [
      "Reading the big number at the top as your loss. It is the distance between the good case and the bad case, so it includes a gain you only collect if difficulty falls. Your loss is the smaller \"Worst case vs today\" line: with the sliders where they start, that is 1.836 BTC, not the 2.525 BTC at the top.",
      "Stretching the period to 20 or 26 weeks while leaving the two difficulty sliders at -2.4% and +7.0%. Those two percentages describe one difficulty change, about two weeks. Over 26 weeks difficulty can move far more than 7%, and the tool will not widen the range for you. You have to do that by hand.",
      "Typing in the sticker rating from the machines. The tool runs your number flat out for every hour. No dead machines, no hours turned down, no pool fee off the top. Sticker figures make every bitcoin number here come out several percent high.",
      "Treating the answer as what happens if difficulty climbs gradually to the top of your range. The tool jumps difficulty straight to the top on day one and holds it there for the whole period. Real difficulty climbs in steps instead. If it climbs in even steps across four difficulty changes, you lose about two thirds of what the tool shows — and less again if most of the rise lands near the end."
    ],
    limits: [
      "It says nothing at all about your costs. There is no power price, no hosting rate and no machine efficiency anywhere in it. It tells you how much bitcoin comes out, not whether you make money. For the cost side, use the hosting cost calculator on this site, at /tools/hosting-effective-rate — the one that works out what you really pay per kilowatt-hour once everything is added up — and put its answer next to this one.",
      "The starting figures are illustrative, not live. There is no data feed behind this site yet, so 127.48 T and the -2.4% to +7.0% range were typed in when the tool was built and have not moved since. Nor does the tool forecast difficulty: the two percentages are yours to set. Look up today's difficulty on a block explorer before you trust any bitcoin figure here, and put the real one in the page address if it has moved, because an out-of-date difficulty figure shifts every bitcoin number on the page by roughly the same percentage. The 3.125 BTC block reward is written into the tool as well, but that one is safe: it halves next in 2028, and the longest period you can set here is 26 weeks, so no run you can set up will cross it.",
      "It tells you how big the hole could be. It does not tell you what to do about it. There are contracts that pay you when difficulty rises. Whether one is worth buying depends on what the contract costs, and this tool does not know that price.",
      "It only fits you if your income moves with difficulty. It does if your pool pays you for the work your machines do, in bitcoin, and you sell that bitcoin to pay bills. It does not if you host other people's machines and charge them per kilowatt-hour. It does not if you have already agreed to hand over a fixed number of bitcoin a month whatever happens, or rented your machines' speed out at an agreed price. In those cases a difficulty rise lands on whoever owns the mining income, and that is not you. Your risk is that they stop paying, which is a different question from the one this page answers."
    ],
  },
  "fleet-payback": {
    article: {
      title: "How long until your machines pay for themselves",
      seoTitle: "Bitcoin mining fleet payback calculator",
      summary: "Work out whether your machines earn back what they cost. The numbers you need, three difficulty paths, and what makes the answer look too good.",
      publishedAt: "2026-08-31",
    },
    whatItIs: "You tell it what your machines cost, how fast they hash, and what you pay for power. It tells you how many months of mining it takes before the bitcoin they earn, once the power bill is paid, covers what you paid for them. Then it does the same sum twice more, with two other guesses about how fast mining gets harder, so you can see which part of the answer comes from your own business and which part is a guess about what everyone else does.",
    whoFor: "For anyone about to buy mining machines. Also for anyone already running some who wants to know whether they will ever pay for themselves. If your machines sit at someone else's site, work out what you really pay per kilowatt-hour before you start, because this tool is only as good as that one number. It is the wrong tool in a few situations, and it will hand you a confident-looking number in all of them. If you are buying hashrate rather than machines — a cloud or hosted-hashrate contract with no hardware of your own — there is nothing you paid up front to earn back, and this arithmetic does not describe your deal. If your machines are already paid for, payback means nothing to you: what you want is the bitcoin price at which they stop covering their own power, and 'Power cost per day' is the part of this page that answers that. If you sell heat, or take curtailment or demand-response payments — money the grid or your host pays you for switching off — or earn anything at all besides mined bitcoin, none of that income exists here, and a fleet that works in real life can look like a loss on this page. And if the four years you care about cross the next halving, expected around spring 2028, read the halving note under Limits before you trust any of it.",
    howToUse: [
      "Before anything else, check the difficulty the tool is starting from. Difficulty — the number that decides how much bitcoin your machines earn — is set here to 127.48 T, where T means trillion, and that is a made-up example rather than today's figure. Look up the real one on mempool.space or any block explorer. If it differs, put the real figure in by adding ?diffT= and the number to the end of the web address, so ?diffT=140 if difficulty is 140 trillion. Everything else moves with this number: start 10% too low and the fleet mines about 10% more bitcoin in the tool than it will on your floor.",
      "Set the four things you already know: 'Fleet hashrate', 'Efficiency', 'All-in power cost' and 'What you paid up front'. Every one of them sits on an invoice, a spec sheet or your pool dashboard, and none of them asks you to predict anything. The sliders move in steps — 50 TH/s for hashrate, $1,000 for what you paid, a tenth of a cent for power — so your exact figure may sit between two steps, or above the top of the slider. When it does, type it into the web address instead: add th=1230, or capex=26450, on the end. Use a question mark before the first one you add and an ampersand before any after that, so ?th=1230&capex=26450. The same trick reaches the two settings that have no slider at all: diffT for the starting difficulty and months for the length of the run, so ?months=60 runs five years instead of four. Anything you set this way holds while you drag the other sliders, but dragging that particular slider snaps it back onto the steps. It works the other way too: copy the web address out of the browser bar and send it to someone, and they see your exact numbers, not your description of them.",
      "Set 'Bitcoin price' to today's price. The tool keeps that same price for all 48 months, so come back afterwards and try a low price and a high one. Then set 'Assumed difficulty growth'. That is the only guess in the tool. Start at 1.5% per month if you have nothing better.",
      "Read the three 'If growth is …' rows rather than the large figure on its own. The tool also does the same sums twice more: once with 2 taken off the percentage you set, and once with 3 added to it. It never goes below 0% per month. So at the default of 1.5% per month, your three rows are 0%, 1.5% and 4.5% per month.",
      "Go to the 'Cash after four years' column, the last one in the table, and find the worst of the three rows. Ask whether your business could take that hit and keep going. If it could not, you are buying too many machines, whatever the middle row says.",
      "Then decide what to do with the three rows. If all three pay back inside the time you care about, difficulty is not your problem, and you can stop worrying about the part of this tool that models it. If the low-growth row pays back and the high-growth row does not, the purchase rests on difficulty behaving: write down the growth rate at which it stops working, then check the real figure against it every couple of months, because within about a year you will know which side you landed on. If none of the three pays back, the difficulty rows have nothing to tell you — go back to the cost per kilowatt-hour and the price per terahash, because those two decide whether a fleet works, and the first of them you can still change."
    ],
    inputs: [
      { label: "Fleet hashrate",
        means: "How much computing your machines do in total, in terahashes per second (TH/s). Double this and you mine twice as much bitcoin. Halve it and you mine half as much.",
        whereToFind: "Your pool dashboard, using the 7-day or 30-day average rather than the number flickering on the screen right now — that average is what you actually get paid on. If you have not bought yet, add up the rated hashrate from each machine's spec sheet. Then take a few percent off. Spec sheet figures are optimistic, and machines run below them in a warm room. One warning about downtime: keep it on one side of the sum only. Your pool's 30-day average hashrate already has your downtime in it, because the machines were off and the average fell. The rate you work out for 'All-in power cost' has the same downtime in it from the other end. Used together they are right: the lower hashrate tells the tool how many kilowatt-hours you actually burned while earning, and the higher rate prices them at what you really paid for the month. Used apart they are wrong. If you enter spec-sheet hashrate as though nothing ever stops, do not also use the higher effective power rate.",
        typical: "A current-generation machine is roughly 200 to 250 TH/s, so the 1,000 TH/s default is about five of them. The slider runs 100 to 20,000 TH/s in steps of 50 TH/s — half a machine up to about a hundred." },
      { label: "Efficiency",
        means: "How much electricity a machine uses to do its work, in joules per terahash (J/TH). Lower is better. With your hashrate it sets your entire electricity bill, and it is used for nothing else in this tool.",
        whereToFind: "The manufacturer's spec sheet, or work it out yourself: the machine's wall power in watts divided by its hashrate in TH/s. A 3,250-watt machine doing 200 TH/s is 16.25 J/TH. Use the wall figure that includes the power supply and the fans, not the chip-only number some sheets quote. If you run underclocked or overclocked, use your own meter reading instead. If your machines are not all the same, the tool still takes one figure, so work out the fleet average. Add up the wall watts of every machine, add up their terahashes per second, and divide the first by the second. Two S19s at 3,250 watts and 200 TH/s each, next to one S21 at 3,500 watts and 200 TH/s, is 10,000 watts over 600 TH/s, which is 16.7 J/TH. 'Fleet hashrate' is the same total, 600 TH/s here, not the biggest machine.",
        typical: "Machines shipping today are 12 to 20 J/TH. A 2021-era S19 is around 30 to 34 J/TH. The slider runs 12 to 40 J/TH in steps of 0.5 J/TH, and starts at 15 J/TH." },
      { label: "All-in power cost",
        means: "What one kilowatt-hour really costs you in US dollars, with everything counted. Do it like this: add up every power bill for one month, then divide by the kilowatt-hours your machines used while they were actually running and mining. That is the number to put in. It is the only running cost in the whole tool, so anything you leave out never shows up anywhere. The boxes all say US dollars, but the tool does not care which currency you use, as long as you use the same one throughout — pounds in here, pounds in 'What you paid up front', and the bitcoin price in pounds too, and the answers come back in pounds. Mixing two currencies quietly ruins the result.",
        whereToFind: "Self-hosted: take one full month's electricity bill — including the standing charge and any demand charge, the extra some suppliers bill you for your single biggest peak in the month — and divide it by the kilowatt-hours on that bill. Hosted: do not use the advertised rate. Add the management fee and any power-factor charge, which is a penalty some sites bill when your electrical load is untidy. Then divide by the kilowatt-hours your machines used while they were actually hashing, not by what they would have used running flat out all month. Hours lost to downtime and curtailment cost you money and earn you nothing, so they push your real rate up. The hosting effective-rate calculator on this site does this sum for you, and it usually lands 10% to 45% above the headline rate.",
        typical: "$0.03 to $0.05 per kilowatt-hour on a good industrial deal, $0.06 to $0.09 hosted once fees and lost hours are counted, $0.15 per kilowatt-hour and up at home. The slider runs $0.02 to $0.15 per kilowatt-hour in steps of $0.001, and starts at $0.045." },
      { label: "What you paid up front",
        means: "Everything you spent in US dollars before the first hash: machines, freight, import duty, power supplies, racks or immersion tanks, the electrician, the deposit. This is the amount your machines have to earn back. The payback month is the month they finish doing it.",
        whereToFind: "Your invoices, added up. Include the parts people forget — freight and duty on a container of machines is not small, and the electrical work is a real part of what the fleet cost you. Do not put anything monthly in here; rent and hosting fees belong in 'All-in power cost', spread across the kilowatt-hours. If the machines are already running, decide which question you are asking before you fill this box in. Put the full invoice total in and the tool judges the purchase as a whole — but it starts difficulty at today's level, so it models the months you have already lived through as kinder than they were. To ask instead how long from today, take everything the fleet has already earned after power off the invoice total, and enter what is left. A fleet that cost $26,000 and has cleared $6,000 after power goes in as $20,000, and the month the tool gives back is months from now.",
        typical: "New machines run roughly $15 to $25 per TH/s, so a 1,000 TH/s fleet is $15,000 to $25,000, and the $20,000 the tool starts with sits in the middle. Second-hand gear can be a third of that. The slider runs $5,000 to $2,000,000 in steps of $1,000." },
      { label: "Bitcoin price",
        means: "The price used to value everything the fleet mines. It stays the same for all 48 months — in this tool, bitcoin never goes up and never goes down. Every money figure on this page is in dollars, and the tool treats each day's mined bitcoin as sold that day at the price you set. If you hold what you mine, the tool is still answering the question you asked — whether the machines earn back what they cost — but it is not telling you what your bitcoin will be worth in four years. That depends on a price nobody here is forecasting.",
        whereToFind: "Any exchange, for today's price. Because it never moves once set, the useful approach is to run the tool three times: at today's price, at a price low enough to worry you, and at one you would be happy with. On the default fleet, $90,000 pays back at 38 months and $110,000 pays back at 23 months, while $70,000 reads 'beyond 48 months' — four years in, that fleet is still $7,915 down. Same machines, same power bill, three different answers.",
        typical: "The slider runs $20,000 to $200,000 in steps of $1,000, and starts at $90,000. The numbers this page starts with are made-up examples, not today's real figures. Set this one yourself before you trust anything." },
      { label: "Assumed difficulty growth",
        means: "Difficulty — the number that decides how much bitcoin your machines earn — rises as more machines switch on around the world. When it rises, you mine less, even though nothing has changed in your shed. This slider is how fast you think it keeps rising each month. Each month's rise stacks on top of the last one, so it adds up fast. 1.5% a month works out at about 20% over a year, and a bit more than double over four years. 4.5% a month is about 70% over a year, and more than eight times over four years.",
        whereToFind: "You cannot look this one up. It is a guess about the future, and that guess is the whole point of the tool. What you can look up is the past: mempool.space and most block explorers show a difficulty history. Compare difficulty a year ago with difficulty today, and work out what the change comes to per month. A 10% rise over a year is about 0.8% a month, 20% is about 1.5% a month, and 70% is about 4.5% a month. Then decide whether the coming year looks like the one behind you.",
        typical: "1% to 3% per month covers most recent stretches. The slider runs 0% to 8% per month in steps of 0.1%, and starts at 1.5% per month. Whatever you pick, the tool also runs it with 2 taken off and 3 added on, and it never lets the low one go below 0% per month. That is deliberately uneven. Difficulty rising faster than you expected is what costs you money, so the tool leans that way." },
      { label: "Starting difficulty",
        means: "Difficulty is the number that decides how much bitcoin your machines earn. This one has no slider. The tool starts at 127.48 T, where T means trillion, and that is a made-up example rather than today's figure. Every bitcoin figure the tool produces moves with it: start 10% too low and the fleet mines about 10% more bitcoin in here than it will on your floor.",
        whereToFind: "mempool.space, or any block explorer, shows the current difficulty. Put the real figure in by adding ?diffT= and the number to the end of the web address, so ?diffT=140 if difficulty is 140 trillion. Use & instead of ? if the address already carries settings from sliders you have moved.",
        typical: "The 127.48 T the tool starts with is in the right area for recent years, but it is not today's. Difficulty changes every two weeks or so, which is why it is worth checking rather than guessing. This is one of the few numbers on this page you can look up exactly." },
    ],
    readingResults: [
      { figure: "Payback — the large blue figure",
        means: "The month when the bitcoin your machines have earned, after you have paid the electricity, first covers what you paid for them. It uses only the difficulty growth number you set yourself, not the two the tool works out either side of it. The small chart underneath shows how much money you are up or down, month by month. The grey line across it is the point where you have got all your money back. The month the blue line crosses that grey line is your payback month.",
        soWhat: "Treat it as the middle of three answers rather than the answer. The chart shows you the shape, not the numbers. The first few months, when you are furthest down, can run off the bottom of the picture. Read the table underneath for the actual figures." },
      { figure: "The three 'If growth is …' rows",
        means: "The same fleet, the same money spent up front and the same bitcoin price, run three times: at the growth rate you set, at that rate with 2 taken off, and at it with 3 added on. You set only the middle one, and the table marks that row 'central'. The tool works out the other two, and never lets the low one go below 0% per month. The rows run from the lowest growth at the top to the highest at the bottom.",
        soWhat: "The gap between the top row and the bottom row is the part of your payback date you have no say in. That part belongs to difficulty. The rest is down to you. If the three rows sit a few months apart, difficulty is a nuisance and you can stop worrying about it. If one row says 24 months and another says 'beyond 48 months', you are not really buying machines. You are betting on what difficulty does. There is one catch in reading that gap. The low-growth row cannot go below 0% per month, so if you set your own rate under 2% per month, that row is no longer two points lower — it becomes 'difficulty stops rising for four years', which has not happened for any length of time. Lower your own guess and the three rows crowd together, and the fleet looks safer than it is. Read the width of the gap as risk only when the rate you set is 2% per month or higher." },
      { figure: "Cash after four years",
        means: "The last column of the table: money in hand after four years, with what you paid up front already taken off. A figure of −$17,282 means that after four years of mining you are still $17,282 down on the whole exercise. It counts each day's mined bitcoin as sold that day at the flat price you set, so it is a money figure, not a bitcoin figure.",
        soWhat: "Take the worst of the three rows and ask whether your business could carry that loss. That question matters more than the payback month. A fleet that pays back in 38 months on the middle row but loses $17,282 on the bottom row is a bet on difficulty — whether or not you meant to place one." },
      { figure: "Power cost per day",
        means: "What the fleet burns in electricity every day at your efficiency and your power price. It is the same every day for all 48 months. 1,000 TH/s at 15 J/TH on $0.045 per kilowatt-hour costs $16.20 a day, and the tool rounds every money figure to the nearest whole dollar, so the row reads $16. A month in this tool is 30.4 days, an even twelfth of a year, so that daily bill is $492 a month. If you are checking this against your own spreadsheet, that is where small differences come from.",
        soWhat: "Compare it against what the fleet earns per day. Anything above it goes towards paying the machines back. If your earnings ever drop below it, you are paying money to mine, and the payback month stops meaning anything. On the default settings, that happens if bitcoin drops under about $33,000. That floor climbs as difficulty climbs, so treat $33,000 as the month-one figure rather than a standing one. On the default settings at 1.5% growth per month, the same fleet needs bitcoin at about $67,000 by month 48 to keep covering its power bill." },
    ],
    walkthrough: {
      title: "Six hosted machines that never catch up",
      setup: "You bought six machines last year — 1,200 TH/s between them, 17.5 J/TH — for $26,000 including freight and racks, and they sit at someone else's site. The contract advertised $0.065 per kilowatt-hour. After the management fee, downtime and curtailment, you have worked out that you really pay about $0.078 for every kilowatt-hour you actually mine with. Bitcoin is $90,000. You want to know whether these machines will ever pay for themselves.",
      steps: [
        "Set 'Fleet hashrate' to 1,200 TH/s, 'Efficiency' to 17.5 J/TH, 'All-in power cost' to $0.078 per kilowatt-hour, 'What you paid up front' to $26,000, 'Bitcoin price' to $90,000 and 'Assumed difficulty growth' to 1.5% per month.",
        "'Power cost per day' reads $39. The fleet draws 21 kilowatts, which is 504 kilowatt-hours a day at $0.078 each — $39.31, which the tool rounds to the nearest dollar on screen. That is the bill whether bitcoin does well or badly.",
        "In the first month those machines mine about 0.00058 bitcoin a day, worth roughly $52 at $90,000. Take off the $39.31 of power and you keep $13.16 a day. A month here is 30.4 days, so that is $400 a month.",
        "$400 a month against $26,000 spent up front is 65 months. That is before difficulty growth is counted at all, and difficulty growth makes every month after this one worse. All three rows read 'beyond 48 months'.",
        "The 'Cash after four years' column shows how badly: −$5,650 if difficulty stops rising completely, −$28,248 at 1.5% per month, −$51,735 at 4.5% per month. None of those figures includes the next halving, which falls inside the four years.",
        "Now drag 'All-in power cost' down to $0.045 per kilowatt-hour and change nothing else. The daily power bill falls to $22.68, which the tool shows as $23. The row where difficulty stops rising finally pays back, at 28 months. The middle row still reads 'beyond 48 months', and ends the four years $3,978 down."
      ],
      takeaway: "Two separate things sank this fleet: the power price, which you can renegotiate or move site over, and the $21.67 per TH/s you paid, which you cannot change now. Difficulty is the third, and it only becomes the interesting question once the first two are right. When a fleet loses money in all three rows, the gap between those rows tells you nothing useful — go and fix the cost per kilowatt-hour instead.",
    },
    mistakes: [
      "Putting the advertised hosting rate into 'All-in power cost'. Your host charges you for your power slot whether the machines run or not. So what you really pay for each kilowatt-hour you mine with is higher than the contract rate. It is commonly 10% to 45% higher once you count management fees, downtime and curtailment. Work that number out first and put that in. On the default fleet, moving from $0.045 to $0.078 per kilowatt-hour turns a payback at 38 months into 'beyond 48 months', four years down $15,044.",
      "Moving 'Fleet hashrate' without moving 'What you paid up front'. The two sliders are entirely independent, and nothing warns you: the tool will happily model 20,000 TH/s bought for $20,000 and report payback in 2 months. Keep them in step. New machines cost roughly $15 to $25 per TH/s, so 20,000 TH/s is $300,000 to $500,000, not $20,000.",
      "Reading 'beyond 48 months' as 'a bit over four years'. It can equally mean never, because the fleet is falling behind and will not catch up. The 'Cash after four years' column tells you which one you are looking at. A figure only a little below zero means you are late. A figure a long way below zero, getting worse as you go down the three rows, means never.",
      "Putting only the electricity bill into 'All-in power cost'. It is the only running cost in the whole tool. Pool fee, site rent, insurance, replacement power supplies and fans, the hours someone spends swapping hashboards — none of it appears anywhere unless you fold it into that one figure. To fold a cost in, turn it into dollars per kilowatt-hour: take what it costs you in a month, and divide by the kilowatt-hours your fleet uses in a month. A 1,000 TH/s fleet at 15 J/TH uses about 10,950 kilowatt-hours a month, so $200 of monthly site rent is about $0.018 per kilowatt-hour on top. A pool fee converts the same way once you make it a dollar figure: 2% of a $1,300 month is $26, which is another $0.002 per kilowatt-hour. Hosting quoted per machine per month is the fleet's whole monthly fee divided by the fleet's monthly kilowatt-hours."
    ],
    limits: [
      "The halving is not in it. The tool pays 3.125 bitcoin per block for all 48 months. In real life the block reward halves roughly every four years, and the next one is expected around spring 2028. On the default settings, halving the reward at month 20 moves payback from 38 months to 'beyond 48 months', and the four-year figure from +$2,291 to −$9,593. If you are counting on anything past spring 2028, this tool is telling you a nicer story than the truth.",
      "Bitcoin price stays the same for all 48 months. Transaction fees — real money you earn on top of the block reward — are not counted at all. One of those makes the answer look better than real life. The other makes it look worse. There is no reason they cancel out. Run the price slider low and high rather than trusting one number.",
      "Nothing breaks, nothing wears out, and tax is nowhere in it. No failed power supplies, no hashboards degrading, no downtime, no heavier cooling load in August. The machines are also worth nothing at the end of the four years, when in practice a working fleet still has resale value. Tax is absent too: income tax on what you mine, the way machines are written down over their life, VAT or duty you can reclaim, whatever falls due when you sell the bitcoin — none of it appears. The payback month here is a figure before tax, and depending on where you operate the real month can land quite a bit later.",
      "Difficulty never falls here. The row where difficulty stops rising is the top row of the three, and the tool never lets it drop below 0% per month. So if the number you set is under 2% per month, that row always reads 0.0% per month, whatever you do with the slider. Real difficulty does fall from time to time, and the tool cannot show you that. The tool also starts difficulty at 127.48 T — that is 127.48 trillion, and a made-up example figure — and it always runs for 48 months. Neither one has a slider. You can change them by putting ?diffT=140 (that means 140 trillion) or ?months=24 on the end of the web address, using & instead of ? if the address already carries settings from sliders you have moved."
    ],
  },
}

export const guideFor = (slug: string): ToolGuideContent | undefined => TOOL_GUIDES[slug]

export const allGuides = (): { slug: string; guide: ToolGuideContent }[] =>
  Object.entries(TOOL_GUIDES).map(([slug, guide]) => ({ slug, guide }))
